import pandas as pd

col_names = [
    'duration',
    'protocol_type',
    'service',
    'flag',
    'src_bytes',
    'dst_bytes',
    'land',
    'wrong_fragment',
    'urgent',
    'hot',
    'num_failed_logins',
    'logged_in',
    'num_compromised',
    'root_shell',
    'su_attempted',
    'num_root',
    'num_file_creations',
    'num_shells',
    'num_access_files',
    'num_outbound_cmds',
    'is_host_login',
    'is_guest_login',
    'count',
    'srv_count',
    'serror_rate',
    'srv_serror_rate',
    'rerror_rate',
    'srv_rerror_rate',
    'same_srv_rate',
    'diff_srv_rate',
    'srv_diff_host_rate',
    'dst_host_count',
    'dst_host_srv_count',
    'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate',
    'dst_host_serror_rate',
    'dst_host_srv_serror_rate',
    'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate',
    'label',
    'difficulty_score'
]

attack_categories = {
    "normal":"normal",
    "neptune":"DoS",
    "back":"DoS",
    "land":"DoS",
    "pod":"DoS",
    "smurf":"DoS",
    "teardrop":"DoS",
    "apache2":"DoS",
    "udpstorm":"DoS",
    "processtable":"DoS",
    "worm":"DoS",
    "satan":"Probe",
    "ipsweep":"Probe",
    "nmap":"Probe",
    "portsweep":"Probe",
    "mscan":"Probe",
    "saint":"Probe",
    "guess_passwd":"R2L",
    "ftp_write":"R2L",
    "imap":"R2L",
    "phf":"R2L",
    "multihop":"R2L",
    "warezmaster":"R2L",
    "warezclient":"R2L",
    "spy":"R2L",
    "xlock":"R2L",
    "xsnoop":"R2L",
    "snmpguess":"R2L",
    "snmpgetattack":"R2L",
    "httptunnel":"R2L",
    "sendmail":"R2L",
    "named":"R2L",
    "buffer_overflow":"U2R",
    "loadmodule":"U2R",
    "perl":"U2R",
    "rootkit":"U2R",
    "sqlattack":"U2R",
    "xterm":"U2R",
    "ps":"U2R",
}

def load_data():
    train_df = pd.read_csv('data/raw/KDDTrain+.txt', header=None, names=col_names)
    test_df = pd.read_csv('data/raw/KDDTest+.txt', header=None, names=col_names)
    train_df = train_df.drop(columns=['difficulty_score'])
    test_df = test_df.drop(columns=['difficulty_score'])
    return (train_df, test_df)
